<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartReportEngine.Application\SmartReportEngine.Application.csproj" />
    <ProjectReference Include="..\SmartReportEngine.Contracts\SmartReportEngine.Contracts.csproj" />
    <ProjectReference Include="..\SmartReportEngine.Infrastructure\SmartReportEngine.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
    <Folder Include="Configurations\" />
  </ItemGroup>

</Project>
